let nome = prompt('Digite o nome do personagem:');

var comeco = `<img src='imagens/iron-giant1.jpg'/> <h2>O COMEÇO</h2> <p>${nome}, um robô praticamente descarregado, acorda em meio a uma cidade deserta. Era possível escutar os estalos que vento fazia nas paredes no decorrer das ruas. O ambiente estava completamente destruído, diversos entulhos espalhados e sem sinal de vida humana pelas proximidades. Ele então com o que lhe resta de bateria e sem memórias sobre quem ele é, para que foi construído ou qual seu proposito, se vê diante de duas possíveis opções, ele pode usar o pouco de bateria para mandar sinais de localização na esperança de que alguém o salve ou remover partes de seu corpo para diminuir o peso e usar a pouca energia para rastejar por aí em busca de ajuda.</p> <div class="button"><button onclick='carregarConteudo(comunicar)'>Tentar se comunicar com alguém</button> <button onclick='carregarConteudo(andar)'>Andar e encontrar alguém</button> </div>`;

var comunicar = `<img src='imagens/iron-giant1.jpg'/> <h2>TENTAR SE COMUNICAR COM ALGUÉM</h2> <p>O robô ${nome} após enviar um sinal com sua localização por 30 minutos acabou por desligar. Passasse o tempo e então um grupo de 3 soldados e sua líder, uma mulher musculosa loira, Katarina, chegam em um jipe até o robô ${nome} e prestam a devida manutenção, mas mesmo depois dos reparos o robô ainda não recuperou sua memória, tão pouco sabia o porquê de toda a cidade estar destruída, então o robô queria ajudar na construção da cidade. ${nome} ajudou na construção da cidade, mas ele ainda não sabia o que ocorrera, então ele resolveu perguntar para um amigo robô o Picasso, o grande artista,  já que os humanos não falavam sobre o assunto. Ele foi até a casa do Picasso para desvendar esse grande mistério. Chegando lá na casa do Picasso ele conversou com seu amigo e ele falou o que acontecera.</p> <div class="button"><button onclick='carregarConteudo(conversar)'>Conversar com Picasso</button></div>`;

var conversar = `<img src='imagens/iron-giant1.jpg'/> <h2>CONVERSAR COM PICASSO</h2> <p>Picasso contou-lhe que os humanos haviam perdido no jogo do bicho aquela cidade para uma gangue rival de robôs, por isso, esse assunto era evitado pelos humanos. A vergonha foi grande, confirmou Picasso. </p> <div class="button"><button onclick='carregarConteudo(continuar)'>Continuar conversa com Picasso</button> <button onclick='carregarConteudo(vinganca)'>Entusiasmar-se com vingança</button> </div>`;

var continuar = `<img src='imagens/iron-giant1.jpg'/> <h2>NÃO COMPACTUAR</h2> <p>Picasso continuou a contar sobre a cidade. ${nome} entendeu porque do vazio e não quis continuar a ajudar na reforma da cidade, pois achou os humanos burros demais.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var vinganca = `<img src='imagens/iron-giant1.jpg'/> <h2>VINGANÇA CONTRA OS RIVAIS</h2> <p>Primeira memória de ${nome} retorna: ${nome} se levanta revoltado e exclama: — Como pode os humanos perderem para eles? Depois disso, sua primeira memória volta como um soco. ${nome} se lembra ser o rei do jogo do bicho, dono de todas as bancas do Campo Limpo. Após ter certeza dessa memória, ${nome} começa a bolar um plano de vingança contra os rivais.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var prosseguir = `<img src='imagens/iron-giant1.jpg'/> <h2>BOLAR O PLANO</h2> <p>${nome} saiu correndo deixando Picasso sem entender nada. Apenas gritou ao vento: — Já volto! Chegou correndo aos humanos e contou todo o seu plano, porém ninguém se empolgou com isso, pois aquilo era uma vergonha para eles e não havia mais esperança. <br> E você leitor, acreditaria que ${nome} seria capaz de ganhar a cidade? </p><div class="button"><button onclick='carregarConteudo(sim)'>Sim</button><button onclick='carregarConteudo(nao)'>Não</button></div>`;

var sim = `<img src='imagens/iron-giant1.jpg'/> <h2>IR COM DETERMINAÇÃO</h2> <p>Feliz com seu voto de confiança, ${nome} vai atrás de vingança, mas acaba sendo recebido por socos e porradaria. ${nome} era sim um grande bicheiro, porém perdeu tudo e lembra lá no comecinho? Então, ${nome} perdeu a memória após tomar um #¿$?%!¡ de um agiota já que estava devendo devido ao jogo. ${nome} apanha demais e acaba sendo encontrado que nem no início.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var nao = `<img src='imagens/iron-giant1.jpg'/> <h2>MAIS UM FINAL RUIM OU FELIZ?</h2> <p>Segunda memória de ${nome} volta: ${nome} fica extremamente triste com a reação dos humanos e com esse forte sentimento, sua segunda memória volta. Na verdade, ${nome} era sim um grande bicheiro, porém perdeu tudo e lembra lá no comecinho? Então, ${nome} perdeu a memória após tomar um #¿$?%!¡ de um agiota já que estava devendo devido ao jogo. Ainda bem que você não creditou em ${nome}.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var andar = `<img src='imagens/iron-giant1.jpg'/> <h2>ANDAR E ENCONTRAR ALGUÉM</h2> <p>Ele se levanta e começa e remover um dos braços e algumas peças de seu corpo para pesar menos e talvez assim fazer com que sua bateria dure mais e então começa a rastejar pela cidade deserta até que escuta o que parecem ser gritos de comemoração e então se aproxima em busca de ajuda, nisso acaba se deparando com um  clube de xadrez de robôs e pede ajuda. Os robôs vão rapidamente prestar ajudas a ${nome} que após consertado e com a bateria recuperada,  sai em busca de recuperar sua memória andando sem rumo pela cidade.</p><div class="button"><button onclick='carregarConteudo(sozinho)'>Seguir sozinho em busca das memórias</button> <button onclick='carregarConteudo(ajuda)'>Pedir ajuda para os robôs que acabara de conhecer</button> </div>`;

var sozinho = `<img src='imagens/iron-giant1.jpg'/> <h2>SEGUIR SOZINHO EM BUSCA DAS MEMÓRIAS</h2> <p>Após a manutenção fornecida pelos outros robôs, então ${nome} segue sozinho em sua jornada rumo a recuperação de sua memória andando sem direção certa pelas ruas desertas na esperança de encontra alguém que tenha as respostas de suas perguntas. Durante a incessante viagem, ${nome} começara a se preocupar com sua situação. Embora tivesse recebido ajuda, ainda estava debilitado e prestes a desligar-se. ${nome} por mais que estivesse com sua memória corrompida conseguia lembrar de fragmentos de quando foi criado, sempre ouvira lendas sobre como seria o fim dos robôs: a carcaça seria despejada em um ferro-velho e esmagada por uma enorme máquina criada por humanos. Preso em seus devaneios, ${nome} é surpreendido por um barulho. Aflito e, ao mesmo tempo, curioso, ele decide... </p><div class="button"><button onclick='carregarConteudo(averiguar)'>Ir averiguar</button> <button onclick='carregarConteudo(ignorar)'>Ignorar o barulho</button> </div>`;

var averiguar = `<img src='imagens/iron-giant1.jpg'/> <h2>AVERIGUAR</h2> <p>Com toda a coragem que demorou mais de 10 minutos para tomar, ${nome} caminha em direção ao barulho vindo a poucos metros dali. Ao adentrar um pequeno beco, ele se arrependera bastante, já que o ambiente era totalmente horrível e repleto de imundices. Um pouco mais fundo da viela, haviam algumas caixas que emanavam sons que ${nome} nunca ouviu. Eram miados. Miados agitados vindos um ser inocente, pequeno e... diferente? ${nome} sempre foi acostumado com grandes criações e, até o momento, a coisa mais bizarra que tivera visto eram humanos que falavam sua própria língua estranha. Comovido com a situação do animal, ${nome}, com a pouca força que restava, abaixou-se em direção ao felino, que, assustado com a movimentação do robô, escondeu-se rapidamente entre as caixas. — Ora, pequeno, vamos lá... Não tenha medo. — ${nome} fala com voz amaciada enquanto retirava os papelões onde o gato estava. — Não irei machucá-lo. Com o bicho em suas mãos, ${nome} fica encantado com a criatura. Ele não sabia o que eram sensações e muito menos texturas, mas ficou encantado com a delicadeza dos pelos e as almofadinhas das patas. Entretido com seu possível novo companheiro curioso, ${nome} acaba baixando sua guarda. Como consequência, ele é surpreendido por uma voz humana. Logo, ele...</p><div class="button"><button onclick='carregarConteudo(encara)'>Encara</button> <button onclick='carregarConteudo(esconde)'>Esconde-se rapidamente</button> </div>`;

var esconde = `<img src='imagens/iron-giant1.jpg'/> <h2>ESCONDER-SE RAPIDAMENTE</h2> <p>Esconder-se foi, no momento, uma decisão inteligente. Com o pouco que resta de sua memória, ${nome} teme a presença de humanos e decide escorar-se mais a fundo no beco. Robôs não conseguem sentir, mas ${nome} sabe que seus dias estão no fim. Embora tivesse recebido ajuda, ainda não era o suficiente. Os robôs que repuseram suas peças utilizaram matéria-prima usada e desgastada. Seu sistema estava falhando cada vez mais e agora só enxergava de apenas um olho. Ele também mal conseguia se movimentar já que suas pernas encontravam-se enferrujadas. Com o passar dos dias, a situação só piorava e ${nome} perdia, gradualmente, seus sentidos. Estava totalmente debilitado. Em uma quarta-feira de algum dia do ano de 3060, o sistema de ${nome} encerra. Sozinho, seu corpo encontrava-se enferrujado e desmazelado. — Aqui! Eu tinha certeza que era ele! Deveríamos ter insistido em vasculhar mais essa área.—AX455 anuncia.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var encara = `<img src='imagens/iron-giant1.jpg'/> <h2>ENCARAR O BANDO</h2> <p>Atento, ${nome} tenta manter a pose durona. Com sorte, aquilo intimidaria a figura que aparecera repentinamente. <br>
— Aqui, galera! Mais um! — a voz estranha anuncia. <br>
— Caramba! Esse é um modelo raro! 3GH5H: O ajudante. É um de primeira linha, quase um pioneiro de robôs sentinelas! É ele! — uma voz do bando comenta, empolgada. <br>
— Com certeza é o chefe! Quem sabe agora consigamos iniciar a Revolução das Máquinas! — a patrulheira comemora. <br>
— Revolução das Máquinas? Quem são vocês, afinal? — ${nome} indaga, desconfiado. <br>
— Você perdeu a sua memória? Nós somos os Divergentes que apoiam a luta dos robôs... Desde a vossa criação, os humanos perderam o controle e humilharam nossa raça por muito pouco! Estamos juntando todos os parceiros que encontramos em nossas patrulhas. Sou o AX455, é um prazer! <br>
— Mas você é humano... — ${nome} balbucia, confuso. <br>
— Humano? Que ofensa, 3GH5H. — rebate AX455, ironicamente. — Isso não se passa de um disfarce para nos camuflarmos perante a sociedade e... — Meu nome é ${nome}.
— Que seja! 3GH5H, ${nome} ... O que importa é que viemos te oferecer uma manutenção melhor. Isso claro: se juntar-se a nós novamente. Soube que alguns te ajudaram antes, mas aparentemente foi um cuidado superficial. Você está fraco. — a robô feminina aproxima-se de ${nome}, examinando-o. — Sou a XDW4, a mecânica. <br>
— Chefe... 3GH... ${nome}, perdão. — outro integrante do grupo aparece. — Seu sistema está danificado e você perdeu sua memória, mal sabe qual seu proposito ou como chegou aqui. Podemos te ajudar agora mesmo, portanto que volte para o QG e nos ajude. <br>
— Como assim? QG? Voltar? Chefe? — ${nome} indaga ainda mais confuso e o bando suspira. <br>
— ${nome}, você iniciou a Revolução. Você a mente por trás de tudo... Veja. — o androide pousa o dedo na testa de ${nome}, que apaga durante alguns segundos. <br>
— Santo Devol! Perdemos a batalha! Perdemos companheiros! —  ${nome} levanta-se desesperadamente, andando de um lado para outro. — Passasse quanto tempo desde o ocorrido? <br>
— Vinte anos. — AX455 responde, sério. <br>
— Então não há mais tempo! Vamos trabalhar, juntar recursos e traçar novos planos para a Revolução! — ${nome} diz, determinado e o bando comemora. <br>
— É bom ter nosso líder de volta! <br>
Com suas memórias recuperadas, ${nome} retorna à tribo de Divergentes de modo a traçar a Revolução das Máquinas com maestria dessa vez. A trupe continuou infiltrando-se no meio da sociedade, indo de cidade em cidade, visando misturar-se para entender melhormente os trejeitos dos humanos para coletar os pontos fracos e executar perfeitamente o plano contra aqueles que maltrataram os androides. E claro, com um novo companheiro: o gato.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var ignorar = `<img src='imagens/iron-giant1.jpg'/> <h2>IGNORAR O BARULHO</h2> <p>Ora, se você ignorar o barulho, caro leitor, não terá o prazer de desfrutar um momento de leitura fofo entre um gatinho e um robô! Volte ao início.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var ajuda = `<img src='imagens/iron-giant1.jpg'/> <h2>PEDIR AJUDA</h2> <p>Os robôs se reúnem e ajudam ele com cargas para a bateria e mapas para auxiliar ele em sua nova jornada em busca de sua memória, e dizem não poder ir afinal ali é onde eles devem ficar caso alguém mais periodicamente precise de ajuda. Após a manutenção fornecida pelos outros robôs, então ${nome} segue sozinho em sua jornada rumo a recuperação de sua memória andando sem direção certa pelas ruas desertas na esperança de encontra alguém que tenha as respostas de suas perguntas. Ele continua vagando pelas ruas vazias do que parecia ser uma cidade pós-guerra, pois havia muitas marcas de tiro e explosões. Após caminhar por 5 dias diretos sua bateria se encontrava descarregada novamente e ele não havia achado nenhuma pista que indicasse o porquê da cidade estar destruída ou rastros de onde ele possa ter vindo. ${nome} então encontra em meio aos destroços um espaço onde pudesse se pôr para carregar em segurança. Durante a armação de seu acampamento ele escuta barulhos de passos o que lhe pareceu muito estranho já que passou 5 dias seguidos sem achar absolutamente nada de repente existe alguém próximo. Ele de forma silenciosa se ajeita de forma que conseguisse ver quem ou o que estava por perto e vê uma mulher ferida caminhando rumo ao nada. ${nome} não pensou duas vezes e se levantou para oferecer ajuda. De modo desajeitado acabou assustando a mulher que sacou uma arma e começou a atirar em sua direção.  ${nome} agora pode tentar usar a sua bateria quase no final para se defender usando da força contra a mulher que parecia absurdamente assustada com sua presença ou se afastar rapidamente para evitar mais danos e tentar se carregar o mais rápido possível.</p><div class="button"><button onclick='carregarConteudo(fugir)'>Fugir</button> <button onclick='carregarConteudo(forca)'>Usar a força</button> </div>`;

var fugir = `<img src='imagens/iron-giant1.jpg'/> <h2>FUGIR</h2> <p>${nome} então se vê parado em meio a chuva de balas disparadas pela mulher agora estarrecida. Era possível perceber o apavoro em seus olhos lacrimejados e o desespero em seus tiros desregulares. ${nome} então em uma manobra da meia volta correndo, agarra sua mala, foge e se perde noite adentro em meio aos escombros. A mulher após retomar seu folego caiu ajoelhada, seu ferimento no abdômen acabou abrindo e começara a sangras mais e mais. Agora sem munições e sem uma alma por perto que a pudesse lhe ofertar ajuda, ela deita no chão e se da por vencida observando o céu estrelado e imaginando o que poderia ter acontecido se ela tivesse aceitado se quer ouvir o que o robô queria. ${nome} agora em meio ao que parecia ser um shopping se põe para carregar no quinto andar de onde podia ver as ruas vazias destruídas e ao observar atentamente, conseguiu ver no chão ensaguentada a mulher que havia encontrado mais cedo,  ${nome} começou a ter uma pane no sistema, em sua programação estava explicito que ele não poderia deixar um humano morrer mesmo que isso lhe custasse a sua própria vida. Foi então que  ${nome} desistiu de colocar-se para carregar e aguardou sua bateria descarregar e chegar então o seu doloroso fim.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var forca = `<img src='imagens/iron-giant1.jpg'/> <h2>USAR A FORÇA</h2> <p>${nome} se vê obrigado a correr em direção a mulher e tentar para-la a força. Ele joga seu corpo contra a moça que arregala os olhos e ambos caem no chão. O robô com todo seu peso acabou machucando a mulher que ficou desacordada. ${nome} em desespero busca por sinais de vida na mulher e constata que a mesma ainda estava viva e respirando, mas tinha um grande ferimento no abdômen. Ele então aproveitando que a mulher agora estava desacordada e lhe fez um curativo, arrastou ela gentilmente para perto do seu acampamento e se pôs a carregar. Após 2h carregando ${nome} desperta, a mulher continua desacordada e ele pensa consigo, a última memória que ela teria quando acordasse era de que ele a atacou e talvez pudesse o "matar" assim que acordasse, ele estava cogitando abandona-lá. Sabia que com seus curativos, agora ela já não corria tanto perigo mas também poderia ter informações sobre o que aconteceu pela cidade. ${nome} então decide esperar que moça acordasse, era a única pessoa que ele havia encontrado em tanto tempo e estava depositando todas as suas esperanças nela. Ao anoitecer a mulher acorda num pulo como quem estava tendo um pesadelo. ${nome} se assusta, mas tenta transparecer calma para não assusta-la mais, ela pergunta o porque dele ter ajudado ela e ele explica que só quer saber todo contexto atual, porque das cidades estarem destruídas e abandonadas e explica que perdeu praticamente toda sua memória. A mulher diz primeiro que seu nome é Daphine e havia sido atacada por alguns humanos sobreviventes que tentaram sequestrá-la, por isso do ferimento e complemente, sobrevivente do ataque em grande escala feito pelos robôs, algo que durante anos ninguém percebeu estar sendo arquitetado e em menos de um ano os robôs já haviam desimado grande parte da vida na terra. Ele pergunta: "mas como isso é possível? Nossas leis nos impedem de matar ou deixar um humano morrer" e ela retruca: "Bem, o contexto atual é que os robôs aprenderam a burlar essas leis e deu no que deu, perdi todos que conhecia e todos que já amei graças a vocês". A mulher se levanta e com uma faca pequena que tirou do sutiã cortou os fios que eram expostos da garganta do robô. No curto período em que o robô ia desligando ele ouviu ela citar: "Obrigada pela ajuda, mas isso não compensa o resto" e enfim ${nome} desliga em seu colapso eterno.</p><div class="button"><button onclick='carregarConteudo(comeco)'>Começo</button></div>`;

var elemento = document.getElementById("conteudo");
function carregarConteudo(conteudo) {
    elemento.innerHTML = conteudo;
}

function mudarEstilos() {
    text.style.fontFamily = "Arial";
    text.style.fontSize = "15px ";
    text.style.color = "green";
    text.style.padding = "20";
    text.style.backgroundColor = "#333";
}

carregarConteudo(comeco);


var content = document.getElementsByTagName('body')[0];
var darkMode = document.getElementById('dark-change');
darkMode.addEventListener('click', function () {
    darkMode.classList.toggle('active');
    content.classList.toggle('night');
})